// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: holo.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HoloRpc_PreAccept_FullMethodName                   = "/holo_store.rpc.HoloRpc/PreAccept"
	HoloRpc_PreAcceptBatch_FullMethodName              = "/holo_store.rpc.HoloRpc/PreAcceptBatch"
	HoloRpc_Accept_FullMethodName                      = "/holo_store.rpc.HoloRpc/Accept"
	HoloRpc_AcceptBatch_FullMethodName                 = "/holo_store.rpc.HoloRpc/AcceptBatch"
	HoloRpc_Commit_FullMethodName                      = "/holo_store.rpc.HoloRpc/Commit"
	HoloRpc_CommitBatch_FullMethodName                 = "/holo_store.rpc.HoloRpc/CommitBatch"
	HoloRpc_Recover_FullMethodName                     = "/holo_store.rpc.HoloRpc/Recover"
	HoloRpc_RecoverBatch_FullMethodName                = "/holo_store.rpc.HoloRpc/RecoverBatch"
	HoloRpc_FetchCommand_FullMethodName                = "/holo_store.rpc.HoloRpc/FetchCommand"
	HoloRpc_ReportExecuted_FullMethodName              = "/holo_store.rpc.HoloRpc/ReportExecuted"
	HoloRpc_LastCommitted_FullMethodName               = "/holo_store.rpc.HoloRpc/LastCommitted"
	HoloRpc_LastExecutedPrefix_FullMethodName          = "/holo_store.rpc.HoloRpc/LastExecutedPrefix"
	HoloRpc_SeedExecutedPrefix_FullMethodName          = "/holo_store.rpc.HoloRpc/SeedExecutedPrefix"
	HoloRpc_Executed_FullMethodName                    = "/holo_store.rpc.HoloRpc/Executed"
	HoloRpc_MarkVisible_FullMethodName                 = "/holo_store.rpc.HoloRpc/MarkVisible"
	HoloRpc_KvGet_FullMethodName                       = "/holo_store.rpc.HoloRpc/KvGet"
	HoloRpc_KvBatchGet_FullMethodName                  = "/holo_store.rpc.HoloRpc/KvBatchGet"
	HoloRpc_KvSet_FullMethodName                       = "/holo_store.rpc.HoloRpc/KvSet"
	HoloRpc_KvBatchSet_FullMethodName                  = "/holo_store.rpc.HoloRpc/KvBatchSet"
	HoloRpc_Join_FullMethodName                        = "/holo_store.rpc.HoloRpc/Join"
	HoloRpc_ClusterState_FullMethodName                = "/holo_store.rpc.HoloRpc/ClusterState"
	HoloRpc_ClusterAddNode_FullMethodName              = "/holo_store.rpc.HoloRpc/ClusterAddNode"
	HoloRpc_ClusterRemoveNode_FullMethodName           = "/holo_store.rpc.HoloRpc/ClusterRemoveNode"
	HoloRpc_ClusterSplitMetaRange_FullMethodName       = "/holo_store.rpc.HoloRpc/ClusterSplitMetaRange"
	HoloRpc_ClusterMetaRebalance_FullMethodName        = "/holo_store.rpc.HoloRpc/ClusterMetaRebalance"
	HoloRpc_RangeSplit_FullMethodName                  = "/holo_store.rpc.HoloRpc/RangeSplit"
	HoloRpc_RangeMerge_FullMethodName                  = "/holo_store.rpc.HoloRpc/RangeMerge"
	HoloRpc_RangeRebalance_FullMethodName              = "/holo_store.rpc.HoloRpc/RangeRebalance"
	HoloRpc_RangeStats_FullMethodName                  = "/holo_store.rpc.HoloRpc/RangeStats"
	HoloRpc_RangeSnapshotLatest_FullMethodName         = "/holo_store.rpc.HoloRpc/RangeSnapshotLatest"
	HoloRpc_RangeWriteLatest_FullMethodName            = "/holo_store.rpc.HoloRpc/RangeWriteLatest"
	HoloRpc_RangeWriteLatestConditional_FullMethodName = "/holo_store.rpc.HoloRpc/RangeWriteLatestConditional"
	HoloRpc_RangeApplyLatest_FullMethodName            = "/holo_store.rpc.HoloRpc/RangeApplyLatest"
	HoloRpc_RangeApplyLatestConditional_FullMethodName = "/holo_store.rpc.HoloRpc/RangeApplyLatestConditional"
	HoloRpc_ClusterFreeze_FullMethodName               = "/holo_store.rpc.HoloRpc/ClusterFreeze"
	HoloRpc_ClusterCheckpointControl_FullMethodName    = "/holo_store.rpc.HoloRpc/ClusterCheckpointControl"
)

// HoloRpcClient is the client API for HoloRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HoloRpcClient interface {
	PreAccept(ctx context.Context, in *PreAcceptRequest, opts ...grpc.CallOption) (*PreAcceptResponse, error)
	PreAcceptBatch(ctx context.Context, in *PreAcceptBatchRequest, opts ...grpc.CallOption) (*PreAcceptBatchResponse, error)
	Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptResponse, error)
	AcceptBatch(ctx context.Context, in *AcceptBatchRequest, opts ...grpc.CallOption) (*AcceptBatchResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	CommitBatch(ctx context.Context, in *CommitBatchRequest, opts ...grpc.CallOption) (*CommitBatchResponse, error)
	Recover(ctx context.Context, in *RecoverRequest, opts ...grpc.CallOption) (*RecoverResponse, error)
	RecoverBatch(ctx context.Context, in *RecoverBatchRequest, opts ...grpc.CallOption) (*RecoverBatchResponse, error)
	FetchCommand(ctx context.Context, in *FetchCommandRequest, opts ...grpc.CallOption) (*FetchCommandResponse, error)
	ReportExecuted(ctx context.Context, in *ReportExecutedRequest, opts ...grpc.CallOption) (*ReportExecutedResponse, error)
	LastCommitted(ctx context.Context, in *LastCommittedRequest, opts ...grpc.CallOption) (*LastCommittedResponse, error)
	LastExecutedPrefix(ctx context.Context, in *LastExecutedPrefixRequest, opts ...grpc.CallOption) (*LastExecutedPrefixResponse, error)
	SeedExecutedPrefix(ctx context.Context, in *SeedExecutedPrefixRequest, opts ...grpc.CallOption) (*SeedExecutedPrefixResponse, error)
	Executed(ctx context.Context, in *ExecutedRequest, opts ...grpc.CallOption) (*ExecutedResponse, error)
	MarkVisible(ctx context.Context, in *MarkVisibleRequest, opts ...grpc.CallOption) (*MarkVisibleResponse, error)
	KvGet(ctx context.Context, in *KvGetRequest, opts ...grpc.CallOption) (*KvGetResponse, error)
	KvBatchGet(ctx context.Context, in *KvBatchGetRequest, opts ...grpc.CallOption) (*KvBatchGetResponse, error)
	KvSet(ctx context.Context, in *KvSetRequest, opts ...grpc.CallOption) (*KvSetResponse, error)
	KvBatchSet(ctx context.Context, in *KvBatchSetRequest, opts ...grpc.CallOption) (*KvBatchSetResponse, error)
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	ClusterState(ctx context.Context, in *ClusterStateRequest, opts ...grpc.CallOption) (*ClusterStateResponse, error)
	ClusterAddNode(ctx context.Context, in *ClusterAddNodeRequest, opts ...grpc.CallOption) (*ClusterAddNodeResponse, error)
	ClusterRemoveNode(ctx context.Context, in *ClusterRemoveNodeRequest, opts ...grpc.CallOption) (*ClusterRemoveNodeResponse, error)
	ClusterSplitMetaRange(ctx context.Context, in *ClusterSplitMetaRangeRequest, opts ...grpc.CallOption) (*ClusterSplitMetaRangeResponse, error)
	ClusterMetaRebalance(ctx context.Context, in *ClusterMetaRebalanceRequest, opts ...grpc.CallOption) (*ClusterMetaRebalanceResponse, error)
	RangeSplit(ctx context.Context, in *RangeSplitRequest, opts ...grpc.CallOption) (*RangeSplitResponse, error)
	RangeMerge(ctx context.Context, in *RangeMergeRequest, opts ...grpc.CallOption) (*RangeMergeResponse, error)
	RangeRebalance(ctx context.Context, in *RangeRebalanceRequest, opts ...grpc.CallOption) (*RangeRebalanceResponse, error)
	RangeStats(ctx context.Context, in *RangeStatsRequest, opts ...grpc.CallOption) (*RangeStatsResponse, error)
	RangeSnapshotLatest(ctx context.Context, in *RangeSnapshotLatestRequest, opts ...grpc.CallOption) (*RangeSnapshotLatestResponse, error)
	RangeWriteLatest(ctx context.Context, in *RangeWriteLatestRequest, opts ...grpc.CallOption) (*RangeWriteLatestResponse, error)
	RangeWriteLatestConditional(ctx context.Context, in *RangeWriteLatestConditionalRequest, opts ...grpc.CallOption) (*RangeWriteLatestConditionalResponse, error)
	RangeApplyLatest(ctx context.Context, in *RangeApplyLatestRequest, opts ...grpc.CallOption) (*RangeApplyLatestResponse, error)
	RangeApplyLatestConditional(ctx context.Context, in *RangeApplyLatestConditionalRequest, opts ...grpc.CallOption) (*RangeApplyLatestConditionalResponse, error)
	ClusterFreeze(ctx context.Context, in *ClusterFreezeRequest, opts ...grpc.CallOption) (*ClusterFreezeResponse, error)
	ClusterCheckpointControl(ctx context.Context, in *ClusterCheckpointControlRequest, opts ...grpc.CallOption) (*ClusterCheckpointControlResponse, error)
}

type holoRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewHoloRpcClient(cc grpc.ClientConnInterface) HoloRpcClient {
	return &holoRpcClient{cc}
}

func (c *holoRpcClient) PreAccept(ctx context.Context, in *PreAcceptRequest, opts ...grpc.CallOption) (*PreAcceptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreAcceptResponse)
	err := c.cc.Invoke(ctx, HoloRpc_PreAccept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) PreAcceptBatch(ctx context.Context, in *PreAcceptBatchRequest, opts ...grpc.CallOption) (*PreAcceptBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreAcceptBatchResponse)
	err := c.cc.Invoke(ctx, HoloRpc_PreAcceptBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptResponse)
	err := c.cc.Invoke(ctx, HoloRpc_Accept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) AcceptBatch(ctx context.Context, in *AcceptBatchRequest, opts ...grpc.CallOption) (*AcceptBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptBatchResponse)
	err := c.cc.Invoke(ctx, HoloRpc_AcceptBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, HoloRpc_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) CommitBatch(ctx context.Context, in *CommitBatchRequest, opts ...grpc.CallOption) (*CommitBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitBatchResponse)
	err := c.cc.Invoke(ctx, HoloRpc_CommitBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) Recover(ctx context.Context, in *RecoverRequest, opts ...grpc.CallOption) (*RecoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverResponse)
	err := c.cc.Invoke(ctx, HoloRpc_Recover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) RecoverBatch(ctx context.Context, in *RecoverBatchRequest, opts ...grpc.CallOption) (*RecoverBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverBatchResponse)
	err := c.cc.Invoke(ctx, HoloRpc_RecoverBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) FetchCommand(ctx context.Context, in *FetchCommandRequest, opts ...grpc.CallOption) (*FetchCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchCommandResponse)
	err := c.cc.Invoke(ctx, HoloRpc_FetchCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) ReportExecuted(ctx context.Context, in *ReportExecutedRequest, opts ...grpc.CallOption) (*ReportExecutedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportExecutedResponse)
	err := c.cc.Invoke(ctx, HoloRpc_ReportExecuted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) LastCommitted(ctx context.Context, in *LastCommittedRequest, opts ...grpc.CallOption) (*LastCommittedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LastCommittedResponse)
	err := c.cc.Invoke(ctx, HoloRpc_LastCommitted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) LastExecutedPrefix(ctx context.Context, in *LastExecutedPrefixRequest, opts ...grpc.CallOption) (*LastExecutedPrefixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LastExecutedPrefixResponse)
	err := c.cc.Invoke(ctx, HoloRpc_LastExecutedPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) SeedExecutedPrefix(ctx context.Context, in *SeedExecutedPrefixRequest, opts ...grpc.CallOption) (*SeedExecutedPrefixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeedExecutedPrefixResponse)
	err := c.cc.Invoke(ctx, HoloRpc_SeedExecutedPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) Executed(ctx context.Context, in *ExecutedRequest, opts ...grpc.CallOption) (*ExecutedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutedResponse)
	err := c.cc.Invoke(ctx, HoloRpc_Executed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) MarkVisible(ctx context.Context, in *MarkVisibleRequest, opts ...grpc.CallOption) (*MarkVisibleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkVisibleResponse)
	err := c.cc.Invoke(ctx, HoloRpc_MarkVisible_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) KvGet(ctx context.Context, in *KvGetRequest, opts ...grpc.CallOption) (*KvGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvGetResponse)
	err := c.cc.Invoke(ctx, HoloRpc_KvGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) KvBatchGet(ctx context.Context, in *KvBatchGetRequest, opts ...grpc.CallOption) (*KvBatchGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvBatchGetResponse)
	err := c.cc.Invoke(ctx, HoloRpc_KvBatchGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) KvSet(ctx context.Context, in *KvSetRequest, opts ...grpc.CallOption) (*KvSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvSetResponse)
	err := c.cc.Invoke(ctx, HoloRpc_KvSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) KvBatchSet(ctx context.Context, in *KvBatchSetRequest, opts ...grpc.CallOption) (*KvBatchSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvBatchSetResponse)
	err := c.cc.Invoke(ctx, HoloRpc_KvBatchSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, HoloRpc_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) ClusterState(ctx context.Context, in *ClusterStateRequest, opts ...grpc.CallOption) (*ClusterStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterStateResponse)
	err := c.cc.Invoke(ctx, HoloRpc_ClusterState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) ClusterAddNode(ctx context.Context, in *ClusterAddNodeRequest, opts ...grpc.CallOption) (*ClusterAddNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterAddNodeResponse)
	err := c.cc.Invoke(ctx, HoloRpc_ClusterAddNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) ClusterRemoveNode(ctx context.Context, in *ClusterRemoveNodeRequest, opts ...grpc.CallOption) (*ClusterRemoveNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterRemoveNodeResponse)
	err := c.cc.Invoke(ctx, HoloRpc_ClusterRemoveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) ClusterSplitMetaRange(ctx context.Context, in *ClusterSplitMetaRangeRequest, opts ...grpc.CallOption) (*ClusterSplitMetaRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterSplitMetaRangeResponse)
	err := c.cc.Invoke(ctx, HoloRpc_ClusterSplitMetaRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) ClusterMetaRebalance(ctx context.Context, in *ClusterMetaRebalanceRequest, opts ...grpc.CallOption) (*ClusterMetaRebalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterMetaRebalanceResponse)
	err := c.cc.Invoke(ctx, HoloRpc_ClusterMetaRebalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) RangeSplit(ctx context.Context, in *RangeSplitRequest, opts ...grpc.CallOption) (*RangeSplitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeSplitResponse)
	err := c.cc.Invoke(ctx, HoloRpc_RangeSplit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) RangeMerge(ctx context.Context, in *RangeMergeRequest, opts ...grpc.CallOption) (*RangeMergeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeMergeResponse)
	err := c.cc.Invoke(ctx, HoloRpc_RangeMerge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) RangeRebalance(ctx context.Context, in *RangeRebalanceRequest, opts ...grpc.CallOption) (*RangeRebalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeRebalanceResponse)
	err := c.cc.Invoke(ctx, HoloRpc_RangeRebalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) RangeStats(ctx context.Context, in *RangeStatsRequest, opts ...grpc.CallOption) (*RangeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeStatsResponse)
	err := c.cc.Invoke(ctx, HoloRpc_RangeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) RangeSnapshotLatest(ctx context.Context, in *RangeSnapshotLatestRequest, opts ...grpc.CallOption) (*RangeSnapshotLatestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeSnapshotLatestResponse)
	err := c.cc.Invoke(ctx, HoloRpc_RangeSnapshotLatest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) RangeWriteLatest(ctx context.Context, in *RangeWriteLatestRequest, opts ...grpc.CallOption) (*RangeWriteLatestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeWriteLatestResponse)
	err := c.cc.Invoke(ctx, HoloRpc_RangeWriteLatest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) RangeWriteLatestConditional(ctx context.Context, in *RangeWriteLatestConditionalRequest, opts ...grpc.CallOption) (*RangeWriteLatestConditionalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeWriteLatestConditionalResponse)
	err := c.cc.Invoke(ctx, HoloRpc_RangeWriteLatestConditional_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) RangeApplyLatest(ctx context.Context, in *RangeApplyLatestRequest, opts ...grpc.CallOption) (*RangeApplyLatestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeApplyLatestResponse)
	err := c.cc.Invoke(ctx, HoloRpc_RangeApplyLatest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) RangeApplyLatestConditional(ctx context.Context, in *RangeApplyLatestConditionalRequest, opts ...grpc.CallOption) (*RangeApplyLatestConditionalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeApplyLatestConditionalResponse)
	err := c.cc.Invoke(ctx, HoloRpc_RangeApplyLatestConditional_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) ClusterFreeze(ctx context.Context, in *ClusterFreezeRequest, opts ...grpc.CallOption) (*ClusterFreezeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterFreezeResponse)
	err := c.cc.Invoke(ctx, HoloRpc_ClusterFreeze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *holoRpcClient) ClusterCheckpointControl(ctx context.Context, in *ClusterCheckpointControlRequest, opts ...grpc.CallOption) (*ClusterCheckpointControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterCheckpointControlResponse)
	err := c.cc.Invoke(ctx, HoloRpc_ClusterCheckpointControl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HoloRpcServer is the server API for HoloRpc service.
// All implementations must embed UnimplementedHoloRpcServer
// for forward compatibility.
type HoloRpcServer interface {
	PreAccept(context.Context, *PreAcceptRequest) (*PreAcceptResponse, error)
	PreAcceptBatch(context.Context, *PreAcceptBatchRequest) (*PreAcceptBatchResponse, error)
	Accept(context.Context, *AcceptRequest) (*AcceptResponse, error)
	AcceptBatch(context.Context, *AcceptBatchRequest) (*AcceptBatchResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	CommitBatch(context.Context, *CommitBatchRequest) (*CommitBatchResponse, error)
	Recover(context.Context, *RecoverRequest) (*RecoverResponse, error)
	RecoverBatch(context.Context, *RecoverBatchRequest) (*RecoverBatchResponse, error)
	FetchCommand(context.Context, *FetchCommandRequest) (*FetchCommandResponse, error)
	ReportExecuted(context.Context, *ReportExecutedRequest) (*ReportExecutedResponse, error)
	LastCommitted(context.Context, *LastCommittedRequest) (*LastCommittedResponse, error)
	LastExecutedPrefix(context.Context, *LastExecutedPrefixRequest) (*LastExecutedPrefixResponse, error)
	SeedExecutedPrefix(context.Context, *SeedExecutedPrefixRequest) (*SeedExecutedPrefixResponse, error)
	Executed(context.Context, *ExecutedRequest) (*ExecutedResponse, error)
	MarkVisible(context.Context, *MarkVisibleRequest) (*MarkVisibleResponse, error)
	KvGet(context.Context, *KvGetRequest) (*KvGetResponse, error)
	KvBatchGet(context.Context, *KvBatchGetRequest) (*KvBatchGetResponse, error)
	KvSet(context.Context, *KvSetRequest) (*KvSetResponse, error)
	KvBatchSet(context.Context, *KvBatchSetRequest) (*KvBatchSetResponse, error)
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	ClusterState(context.Context, *ClusterStateRequest) (*ClusterStateResponse, error)
	ClusterAddNode(context.Context, *ClusterAddNodeRequest) (*ClusterAddNodeResponse, error)
	ClusterRemoveNode(context.Context, *ClusterRemoveNodeRequest) (*ClusterRemoveNodeResponse, error)
	ClusterSplitMetaRange(context.Context, *ClusterSplitMetaRangeRequest) (*ClusterSplitMetaRangeResponse, error)
	ClusterMetaRebalance(context.Context, *ClusterMetaRebalanceRequest) (*ClusterMetaRebalanceResponse, error)
	RangeSplit(context.Context, *RangeSplitRequest) (*RangeSplitResponse, error)
	RangeMerge(context.Context, *RangeMergeRequest) (*RangeMergeResponse, error)
	RangeRebalance(context.Context, *RangeRebalanceRequest) (*RangeRebalanceResponse, error)
	RangeStats(context.Context, *RangeStatsRequest) (*RangeStatsResponse, error)
	RangeSnapshotLatest(context.Context, *RangeSnapshotLatestRequest) (*RangeSnapshotLatestResponse, error)
	RangeWriteLatest(context.Context, *RangeWriteLatestRequest) (*RangeWriteLatestResponse, error)
	RangeWriteLatestConditional(context.Context, *RangeWriteLatestConditionalRequest) (*RangeWriteLatestConditionalResponse, error)
	RangeApplyLatest(context.Context, *RangeApplyLatestRequest) (*RangeApplyLatestResponse, error)
	RangeApplyLatestConditional(context.Context, *RangeApplyLatestConditionalRequest) (*RangeApplyLatestConditionalResponse, error)
	ClusterFreeze(context.Context, *ClusterFreezeRequest) (*ClusterFreezeResponse, error)
	ClusterCheckpointControl(context.Context, *ClusterCheckpointControlRequest) (*ClusterCheckpointControlResponse, error)
	mustEmbedUnimplementedHoloRpcServer()
}

// UnimplementedHoloRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHoloRpcServer struct{}

func (UnimplementedHoloRpcServer) PreAccept(context.Context, *PreAcceptRequest) (*PreAcceptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreAccept not implemented")
}
func (UnimplementedHoloRpcServer) PreAcceptBatch(context.Context, *PreAcceptBatchRequest) (*PreAcceptBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreAcceptBatch not implemented")
}
func (UnimplementedHoloRpcServer) Accept(context.Context, *AcceptRequest) (*AcceptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedHoloRpcServer) AcceptBatch(context.Context, *AcceptBatchRequest) (*AcceptBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptBatch not implemented")
}
func (UnimplementedHoloRpcServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedHoloRpcServer) CommitBatch(context.Context, *CommitBatchRequest) (*CommitBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitBatch not implemented")
}
func (UnimplementedHoloRpcServer) Recover(context.Context, *RecoverRequest) (*RecoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recover not implemented")
}
func (UnimplementedHoloRpcServer) RecoverBatch(context.Context, *RecoverBatchRequest) (*RecoverBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoverBatch not implemented")
}
func (UnimplementedHoloRpcServer) FetchCommand(context.Context, *FetchCommandRequest) (*FetchCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchCommand not implemented")
}
func (UnimplementedHoloRpcServer) ReportExecuted(context.Context, *ReportExecutedRequest) (*ReportExecutedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportExecuted not implemented")
}
func (UnimplementedHoloRpcServer) LastCommitted(context.Context, *LastCommittedRequest) (*LastCommittedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LastCommitted not implemented")
}
func (UnimplementedHoloRpcServer) LastExecutedPrefix(context.Context, *LastExecutedPrefixRequest) (*LastExecutedPrefixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LastExecutedPrefix not implemented")
}
func (UnimplementedHoloRpcServer) SeedExecutedPrefix(context.Context, *SeedExecutedPrefixRequest) (*SeedExecutedPrefixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SeedExecutedPrefix not implemented")
}
func (UnimplementedHoloRpcServer) Executed(context.Context, *ExecutedRequest) (*ExecutedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Executed not implemented")
}
func (UnimplementedHoloRpcServer) MarkVisible(context.Context, *MarkVisibleRequest) (*MarkVisibleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkVisible not implemented")
}
func (UnimplementedHoloRpcServer) KvGet(context.Context, *KvGetRequest) (*KvGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvGet not implemented")
}
func (UnimplementedHoloRpcServer) KvBatchGet(context.Context, *KvBatchGetRequest) (*KvBatchGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvBatchGet not implemented")
}
func (UnimplementedHoloRpcServer) KvSet(context.Context, *KvSetRequest) (*KvSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvSet not implemented")
}
func (UnimplementedHoloRpcServer) KvBatchSet(context.Context, *KvBatchSetRequest) (*KvBatchSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvBatchSet not implemented")
}
func (UnimplementedHoloRpcServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedHoloRpcServer) ClusterState(context.Context, *ClusterStateRequest) (*ClusterStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterState not implemented")
}
func (UnimplementedHoloRpcServer) ClusterAddNode(context.Context, *ClusterAddNodeRequest) (*ClusterAddNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterAddNode not implemented")
}
func (UnimplementedHoloRpcServer) ClusterRemoveNode(context.Context, *ClusterRemoveNodeRequest) (*ClusterRemoveNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterRemoveNode not implemented")
}
func (UnimplementedHoloRpcServer) ClusterSplitMetaRange(context.Context, *ClusterSplitMetaRangeRequest) (*ClusterSplitMetaRangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterSplitMetaRange not implemented")
}
func (UnimplementedHoloRpcServer) ClusterMetaRebalance(context.Context, *ClusterMetaRebalanceRequest) (*ClusterMetaRebalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterMetaRebalance not implemented")
}
func (UnimplementedHoloRpcServer) RangeSplit(context.Context, *RangeSplitRequest) (*RangeSplitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RangeSplit not implemented")
}
func (UnimplementedHoloRpcServer) RangeMerge(context.Context, *RangeMergeRequest) (*RangeMergeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RangeMerge not implemented")
}
func (UnimplementedHoloRpcServer) RangeRebalance(context.Context, *RangeRebalanceRequest) (*RangeRebalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RangeRebalance not implemented")
}
func (UnimplementedHoloRpcServer) RangeStats(context.Context, *RangeStatsRequest) (*RangeStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RangeStats not implemented")
}
func (UnimplementedHoloRpcServer) RangeSnapshotLatest(context.Context, *RangeSnapshotLatestRequest) (*RangeSnapshotLatestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RangeSnapshotLatest not implemented")
}
func (UnimplementedHoloRpcServer) RangeWriteLatest(context.Context, *RangeWriteLatestRequest) (*RangeWriteLatestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RangeWriteLatest not implemented")
}
func (UnimplementedHoloRpcServer) RangeWriteLatestConditional(context.Context, *RangeWriteLatestConditionalRequest) (*RangeWriteLatestConditionalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RangeWriteLatestConditional not implemented")
}
func (UnimplementedHoloRpcServer) RangeApplyLatest(context.Context, *RangeApplyLatestRequest) (*RangeApplyLatestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RangeApplyLatest not implemented")
}
func (UnimplementedHoloRpcServer) RangeApplyLatestConditional(context.Context, *RangeApplyLatestConditionalRequest) (*RangeApplyLatestConditionalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RangeApplyLatestConditional not implemented")
}
func (UnimplementedHoloRpcServer) ClusterFreeze(context.Context, *ClusterFreezeRequest) (*ClusterFreezeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterFreeze not implemented")
}
func (UnimplementedHoloRpcServer) ClusterCheckpointControl(context.Context, *ClusterCheckpointControlRequest) (*ClusterCheckpointControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterCheckpointControl not implemented")
}
func (UnimplementedHoloRpcServer) mustEmbedUnimplementedHoloRpcServer() {}
func (UnimplementedHoloRpcServer) testEmbeddedByValue()                 {}

// UnsafeHoloRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HoloRpcServer will
// result in compilation errors.
type UnsafeHoloRpcServer interface {
	mustEmbedUnimplementedHoloRpcServer()
}

func RegisterHoloRpcServer(s grpc.ServiceRegistrar, srv HoloRpcServer) {
	// If the following call panics, it indicates UnimplementedHoloRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HoloRpc_ServiceDesc, srv)
}

func _HoloRpc_PreAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreAcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).PreAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_PreAccept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).PreAccept(ctx, req.(*PreAcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_PreAcceptBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreAcceptBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).PreAcceptBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_PreAcceptBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).PreAcceptBatch(ctx, req.(*PreAcceptBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_Accept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).Accept(ctx, req.(*AcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_AcceptBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).AcceptBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_AcceptBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).AcceptBatch(ctx, req.(*AcceptBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_CommitBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).CommitBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_CommitBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).CommitBatch(ctx, req.(*CommitBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_Recover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).Recover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_Recover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).Recover(ctx, req.(*RecoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_RecoverBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).RecoverBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_RecoverBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).RecoverBatch(ctx, req.(*RecoverBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_FetchCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).FetchCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_FetchCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).FetchCommand(ctx, req.(*FetchCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_ReportExecuted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportExecutedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).ReportExecuted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_ReportExecuted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).ReportExecuted(ctx, req.(*ReportExecutedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_LastCommitted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastCommittedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).LastCommitted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_LastCommitted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).LastCommitted(ctx, req.(*LastCommittedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_LastExecutedPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastExecutedPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).LastExecutedPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_LastExecutedPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).LastExecutedPrefix(ctx, req.(*LastExecutedPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_SeedExecutedPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedExecutedPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).SeedExecutedPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_SeedExecutedPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).SeedExecutedPrefix(ctx, req.(*SeedExecutedPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_Executed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).Executed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_Executed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).Executed(ctx, req.(*ExecutedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_MarkVisible_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkVisibleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).MarkVisible(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_MarkVisible_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).MarkVisible(ctx, req.(*MarkVisibleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_KvGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).KvGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_KvGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).KvGet(ctx, req.(*KvGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_KvBatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBatchGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).KvBatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_KvBatchGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).KvBatchGet(ctx, req.(*KvBatchGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_KvSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).KvSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_KvSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).KvSet(ctx, req.(*KvSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_KvBatchSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBatchSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).KvBatchSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_KvBatchSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).KvBatchSet(ctx, req.(*KvBatchSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_ClusterState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).ClusterState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_ClusterState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).ClusterState(ctx, req.(*ClusterStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_ClusterAddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterAddNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).ClusterAddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_ClusterAddNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).ClusterAddNode(ctx, req.(*ClusterAddNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_ClusterRemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterRemoveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).ClusterRemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_ClusterRemoveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).ClusterRemoveNode(ctx, req.(*ClusterRemoveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_ClusterSplitMetaRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterSplitMetaRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).ClusterSplitMetaRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_ClusterSplitMetaRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).ClusterSplitMetaRange(ctx, req.(*ClusterSplitMetaRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_ClusterMetaRebalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterMetaRebalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).ClusterMetaRebalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_ClusterMetaRebalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).ClusterMetaRebalance(ctx, req.(*ClusterMetaRebalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_RangeSplit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeSplitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).RangeSplit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_RangeSplit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).RangeSplit(ctx, req.(*RangeSplitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_RangeMerge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeMergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).RangeMerge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_RangeMerge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).RangeMerge(ctx, req.(*RangeMergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_RangeRebalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeRebalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).RangeRebalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_RangeRebalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).RangeRebalance(ctx, req.(*RangeRebalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_RangeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).RangeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_RangeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).RangeStats(ctx, req.(*RangeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_RangeSnapshotLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeSnapshotLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).RangeSnapshotLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_RangeSnapshotLatest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).RangeSnapshotLatest(ctx, req.(*RangeSnapshotLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_RangeWriteLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeWriteLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).RangeWriteLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_RangeWriteLatest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).RangeWriteLatest(ctx, req.(*RangeWriteLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_RangeWriteLatestConditional_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeWriteLatestConditionalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).RangeWriteLatestConditional(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_RangeWriteLatestConditional_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).RangeWriteLatestConditional(ctx, req.(*RangeWriteLatestConditionalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_RangeApplyLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeApplyLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).RangeApplyLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_RangeApplyLatest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).RangeApplyLatest(ctx, req.(*RangeApplyLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_RangeApplyLatestConditional_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeApplyLatestConditionalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).RangeApplyLatestConditional(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_RangeApplyLatestConditional_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).RangeApplyLatestConditional(ctx, req.(*RangeApplyLatestConditionalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_ClusterFreeze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterFreezeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).ClusterFreeze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_ClusterFreeze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).ClusterFreeze(ctx, req.(*ClusterFreezeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HoloRpc_ClusterCheckpointControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterCheckpointControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoloRpcServer).ClusterCheckpointControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoloRpc_ClusterCheckpointControl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoloRpcServer).ClusterCheckpointControl(ctx, req.(*ClusterCheckpointControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HoloRpc_ServiceDesc is the grpc.ServiceDesc for HoloRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HoloRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "holo_store.rpc.HoloRpc",
	HandlerType: (*HoloRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreAccept",
			Handler:    _HoloRpc_PreAccept_Handler,
		},
		{
			MethodName: "PreAcceptBatch",
			Handler:    _HoloRpc_PreAcceptBatch_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _HoloRpc_Accept_Handler,
		},
		{
			MethodName: "AcceptBatch",
			Handler:    _HoloRpc_AcceptBatch_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _HoloRpc_Commit_Handler,
		},
		{
			MethodName: "CommitBatch",
			Handler:    _HoloRpc_CommitBatch_Handler,
		},
		{
			MethodName: "Recover",
			Handler:    _HoloRpc_Recover_Handler,
		},
		{
			MethodName: "RecoverBatch",
			Handler:    _HoloRpc_RecoverBatch_Handler,
		},
		{
			MethodName: "FetchCommand",
			Handler:    _HoloRpc_FetchCommand_Handler,
		},
		{
			MethodName: "ReportExecuted",
			Handler:    _HoloRpc_ReportExecuted_Handler,
		},
		{
			MethodName: "LastCommitted",
			Handler:    _HoloRpc_LastCommitted_Handler,
		},
		{
			MethodName: "LastExecutedPrefix",
			Handler:    _HoloRpc_LastExecutedPrefix_Handler,
		},
		{
			MethodName: "SeedExecutedPrefix",
			Handler:    _HoloRpc_SeedExecutedPrefix_Handler,
		},
		{
			MethodName: "Executed",
			Handler:    _HoloRpc_Executed_Handler,
		},
		{
			MethodName: "MarkVisible",
			Handler:    _HoloRpc_MarkVisible_Handler,
		},
		{
			MethodName: "KvGet",
			Handler:    _HoloRpc_KvGet_Handler,
		},
		{
			MethodName: "KvBatchGet",
			Handler:    _HoloRpc_KvBatchGet_Handler,
		},
		{
			MethodName: "KvSet",
			Handler:    _HoloRpc_KvSet_Handler,
		},
		{
			MethodName: "KvBatchSet",
			Handler:    _HoloRpc_KvBatchSet_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _HoloRpc_Join_Handler,
		},
		{
			MethodName: "ClusterState",
			Handler:    _HoloRpc_ClusterState_Handler,
		},
		{
			MethodName: "ClusterAddNode",
			Handler:    _HoloRpc_ClusterAddNode_Handler,
		},
		{
			MethodName: "ClusterRemoveNode",
			Handler:    _HoloRpc_ClusterRemoveNode_Handler,
		},
		{
			MethodName: "ClusterSplitMetaRange",
			Handler:    _HoloRpc_ClusterSplitMetaRange_Handler,
		},
		{
			MethodName: "ClusterMetaRebalance",
			Handler:    _HoloRpc_ClusterMetaRebalance_Handler,
		},
		{
			MethodName: "RangeSplit",
			Handler:    _HoloRpc_RangeSplit_Handler,
		},
		{
			MethodName: "RangeMerge",
			Handler:    _HoloRpc_RangeMerge_Handler,
		},
		{
			MethodName: "RangeRebalance",
			Handler:    _HoloRpc_RangeRebalance_Handler,
		},
		{
			MethodName: "RangeStats",
			Handler:    _HoloRpc_RangeStats_Handler,
		},
		{
			MethodName: "RangeSnapshotLatest",
			Handler:    _HoloRpc_RangeSnapshotLatest_Handler,
		},
		{
			MethodName: "RangeWriteLatest",
			Handler:    _HoloRpc_RangeWriteLatest_Handler,
		},
		{
			MethodName: "RangeWriteLatestConditional",
			Handler:    _HoloRpc_RangeWriteLatestConditional_Handler,
		},
		{
			MethodName: "RangeApplyLatest",
			Handler:    _HoloRpc_RangeApplyLatest_Handler,
		},
		{
			MethodName: "RangeApplyLatestConditional",
			Handler:    _HoloRpc_RangeApplyLatestConditional_Handler,
		},
		{
			MethodName: "ClusterFreeze",
			Handler:    _HoloRpc_ClusterFreeze_Handler,
		},
		{
			MethodName: "ClusterCheckpointControl",
			Handler:    _HoloRpc_ClusterCheckpointControl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "holo.proto",
}
